//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a ete genere par un outil.
//     Version du runtime :4.0.30319.239
//
//     Les modifications apportees a ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est regenere.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBattleView.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typee destinee, entre autres, a la consultation des chaînes localisees.
    /// </summary>
    // Cette classe a ete generee automatiquement par la classe StronglyTypedResourceBuilder
    // a l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis reexecutez ResGen
    // avec l'option /str ou regenerez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisee par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceBattleView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriete CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources a l'aide de cette classe de ressource fortement typee.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
