//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a ete genere par un outil.
//     Version du runtime :4.0.30319.239
//
//     Les modifications apportees a ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est regenere.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBattleView.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
