//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

#include<vector>
#include "..\Abstrait\ArtefactSquare.h"
#include <iostream>

	/*! \class ArtefactSquareStd
	* \brief classe implementant ArtefactSquare, representant une case contenant un artefact
	*
	*/
	class DLL ArtefactSquareStd : public ArtefactSquare
	{

		public :

			ArtefactSquareStd();
			bool isAccessible();
			void printConsole();
			SquareType getType();
			void doAction(Player* p);

	}; 
	EXTERNC DLL  ArtefactSquareStd* ArtefactSquareStd_New();
	EXTERNC DLL  void ArtefactSquareStd_Delete(ArtefactSquareStd* a);