//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

#include<vector>
#include "..\Abstrait\EnergyStationSquare.h"
#include <iostream>

	/*! \class EnergyStationSquareStd
	* \brief classe implementant EnergyStationSquare, representant une case contenant une energie
	*
	*/
	class DLL EnergyStationSquareStd : public EnergyStationSquare
	{

		public :
		EnergyStationSquareStd();
		bool isAccessible();
		void printConsole();
		SquareType getType();
		void doAction(Player* p);

	}; 
	EXTERNC DLL EnergyStationSquareStd* EnergyStationSquareStd_New();
	EXTERNC DLL void EnergyStationSquareStd_Delete(EnergyStationSquareStd* e);