//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include<vector>
#include "..\Abstrait\GameDices.h"
#include <time.h>


/*!
* \class GameDicesStd
* \implements Gamedices
* \brief implementation des des
*
*/
	class DLL GameDicesStd : public GameDices
	{


		protected :
			int d1;		/*!< De 1*/
			int d2;		/*!< De 2*/
			int maxValue;	/*!< valeur max des des*/

		public :
			GameDicesStd();
			void reset();
			int rollFirstDice();
			int rollSecondDice();
			int getFirstDiceValue();
			int getSecondDiceValue();

	}; 

	EXTERNC DLL GameDicesStd* GameDicesStd_New();
	EXTERNC DLL void GameDicesStd_Delete(GameDicesStd* gd);
 
