//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

#include<vector>
#include "..\Abstrait\OrbitalStationSquare.h"
#include <iostream>

	/*! \class OrbitalStationSquareStd
	* \brief classe representant une case contenant une station orbitale
	* \implements OrbitalStationSquare
	*
	*/
	class DLL OrbitalStationSquareStd : public OrbitalStationSquare
	{
	private:
		char* color; /*!< couleur de la station orbitale*/

		public :
			
		OrbitalStationSquareStd();
		bool isAccessible();
		void printConsole();
		SquareType getType();
		void doAction(Player* p);
	}; 
	EXTERNC DLL OrbitalStationSquareStd* OrbitalStationSquareStd_New();
	EXTERNC DLL void OrbitalStationSquareStd_Delete(OrbitalStationSquareStd* e);
