//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include<vector>
#include "..\Abstrait\GameStatus.h"

/*! \class WaitStatus
* \brief classe representant, durant une partie, l'etat "un joueur attend son tour"
* \implements GameStatus
*
*/
	class DLL WaitStatus : public GameStatus
	{

		private:
		Game* game;	/*!< La partie dans laquelle l'etat est associe*/
		public :
			WaitStatus();
			WaitStatus(Game* g);
			~WaitStatus();
			void doAction(double posx,double posy,int playerNb);
			GameStatusType getType();

	}; 
	EXTERNC DLL WaitStatus* WaitStatus_New();
	EXTERNC DLL void WaitStatus_Delete(WaitStatus* a);
