//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Game.h"
#include "Spaceship.h"

/*! \interface GameBuilder
* \brief interface du monteur de Game, sert a initialiser le moteur du jeu a chaque nouveau lancement
*
*/
class GameBuilder 
{
	public:
		virtual Game* createGame(int nbPlayers,int nbArtefact,std::string mapFile,std::vector<Color>& colorVec,std::vector<int>& teamVec) = 0;
		virtual int getOrbitalPosX(Color c,int longueur, int hauteur) = 0;
		virtual int getOrbitalPosY(Color c,int longueur, int hauteur) = 0;
		virtual void setPosShip(Spaceship* s,Color c,int longueur, int hauteur) = 0;
};





