//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

#include <list>

#include "Square.h"

/*! \interface Map
* \brief Interface de ce qui represente une map
*
*/
	class DLL Map 
	{
		public:
		//virtual void getAccessiblePositions(Position pos)=0;
		virtual void addSquare(int posx, int posy, Square* s)=0;
		virtual void printConsole() = 0;
		virtual int getLongueur() = 0;
		virtual int getHauteur() = 0;
		virtual SquareType getSquareType(int x,int y) = 0;
		virtual void setLongueur(int l) = 0;
		virtual void setHauteur(int h) = 0;
		virtual void initialize (int longueur, int haut) = 0;
		virtual Square* getSquare(int posx, int posy) = 0;
		virtual bool isValidMap() = 0;
		virtual void setValidMap(bool b) = 0;
	};



