//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

namespace ModeleAbstrait

/*! \interface Observable
* \brief à implémenter pour devenir observable
*
*/{
	class Observable 
	{
		public:
		virtual void notifyObs()=0;

		virtual void addObserver(Observer o)()=0;

		virtual void removeObserver(object Observer o)=0;

	};
	EXTERNC DLL void OBSERVABLE_notifyObs(Observable*);
	EXTERNC DLL void OBSERVABLE_addObserver(Observer o)(Observable*);
	EXTERNC DLL void OBSERVABLE_removeObserver(Observable*, object Observer o);
}

