//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Spaceship.h"
#include "SpaceshipFactory.h"

/**
 * \enum Color
 * \brief les 4 couleurs utilisees pour distinguer les joueurs
 *
 */
enum Color {
     Red = 0,
     Blue = 1,
     Green = 2,
     Yellow = 3
};
/*! \interface Player
* \brief interface d'un joueur
*
*/
class DLL Player 
{
	

	public:
	virtual void winArtefact() = 0;
	virtual Color getColor() = 0;
	virtual int getPlayerPosX() = 0;
	virtual int getPlayerPosY() = 0;
	virtual int getNbArtefacts() = 0;
	virtual bool getPlayerPossesArtefact() = 0;
	virtual int getPlayerShotsRemaining() = 0;
	virtual Spaceship* getSpaceship() = 0;
	virtual bool isOnHisOrbitalStation() = 0;
	virtual void restoreMothership() = 0;
	virtual void replaceSpaceship(Spaceship* newSpaceship) = 0;


};



