//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Spaceship.h"

/*! \interface SpaceshipFactory
* \brief interface du monteur de Spaceship
*
*/
class DLL SpaceshipFactory 
{
	public:
	virtual Spaceship* createBattlecruiser()=0;
	virtual Spaceship* createMothership()=0;
	virtual Spaceship* createRescuecab()=0;
	virtual Spaceship* createNextSpaceship(Spaceship* s)=0;

};



