//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

#include <iostream>

/*!
 * \enum SpaceshipType
 * \brief Types de vaisseaux possibles
 *
 */
enum SpaceshipType {
     MothershipType,
     BattlecruiserType,
     RescuecabType
};

/*! \class Spaceship
* \brief interface representant un vaisseau
*
*/
class DLL Spaceship
{

	protected :

		int posx;					/*!< Abcisse de la position du vaisseau */
		int posy;					/*!< Ordonnee de la position du vaiseau */
		int diceNumber;				/*!< ... */
		int remainingShotsNumber;	/*!< Nombre de tirs restants */
		int maxShotsNumber;			/*!< Nombre de tirs max */
		int reboundNumber;			/*!< Nombre de rebonds que peut faire un tir */
		bool possesArtefact;		/*!< Indique si le vaisseau transporte (ou non) un artefact */

	public :
		Spaceship(void);
		~Spaceship(void);
		virtual void takeArtefact();
		virtual bool hasArtefact();
		virtual void chargeLaser();
		virtual void depositArtefact();
		virtual void printConsole();
		virtual void printType();
		virtual SpaceshipType getType() = 0;
		virtual int getPosX();
		virtual int getPosY();
		virtual int getShotsRemaining();
		virtual int getReboundNumber();
		virtual void decreaseShotsRemaining();
		virtual bool canShoot();
		virtual void setPosX(int x);
		virtual void setPosY(int y);
		virtual void move(int x,int y);

}; 

