//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Player.h"

/*!
 * \enum SquareType
 * \brief Types de cases possibles
 *
 */
enum SquareType {
     EmptySquareType,
     OrbitalStationSquareType,
     EnergyStationSquareType,
	 ArtefactSquareType,
	 AsteroidSquareType
};

	/*! \interface Square
	* \brief interface representant une case
	*
	*  Interface a implementer
	*/
	class DLL Square 
	{
		public:
		virtual bool isAccessible()=0;
		virtual SquareType getType() = 0;
		virtual void printConsole() = 0;
		virtual void doAction(Player* p) = 0;
	};


